Company/Company/Controllers/DepartamentsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using CompanyASP.Data;
using CompanyASP.Models;
using CompanyASP.ViewModel;

namespace CompanyASP.Controllers
{
    public class DepartamentsController : Controller
    {
        private readonly CompanyContext _context;
        private int pageSize = 10;

        public DepartamentsController(CompanyContext context)
        {
            _context = context;
        }

        // GET: Departaments
        public IActionResult Index(int page = 1)
        {
            IQueryable<Departament> companyContext = _context.Departaments;

            //разбиение на страницы
            var count = companyContext.Count();
            companyContext = companyContext.Skip((page - 1) * pageSize).Take(pageSize);

            //формирование представления
            DepartamentViewModel departament = new DepartamentViewModel
            {
                Departaments = companyContext,
                PageViewModel = new PageViewModel(count, page, pageSize),
            };
            return View(departament);
        }

        // GET: Departaments/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var departament = await _context.Departaments
                .FirstOrDefaultAsync(m => m.Id == id);
            if (departament == null)
            {
                return NotFound();
            }

            return View(departament);
        }

        // GET: Departaments/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: Departaments/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id,FullName,CountEmployee")] Departament departament)
        {
            if (ModelState.IsValid)
            {
                _context.Add(departament);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(departament);
        }

        // GET: Departaments/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var departament = await _context.Departaments.FindAsync(id);
            if (departament == null)
            {
                return NotFound();
            }
            return View(departament);
        }

        // POST: Departaments/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Id,FullName,CountEmployee")] Departament departament)
        {
            if (id != departament.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(departament);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!DepartamentExists(departament.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(departament);
        }

        // GET: Departaments/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var departament = await _context.Departaments
                .FirstOrDefaultAsync(m => m.Id == id);
            if (departament == null)
            {
                return NotFound();
            }

            return View(departament);
        }

        // POST: Departaments/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var departament = await _context.Departaments.FindAsync(id);
            _context.Departaments.Remove(departament);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool DepartamentExists(int id)
        {
            return _context.Departaments.Any(e => e.Id == id);
        }
    }
}

Company/Company/Controllers/EmployeesController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using CompanyASP.Data;
using CompanyASP.Models;
using CompanyASP.ViewModel;
using CompanyASP.ViewModel.SortedEmployee;

namespace CompanyASP.Controllers
{
    public class EmployeesController : Controller
    {
        private readonly CompanyContext _context;
        private int pageSize = 10;

        public EmployeesController(CompanyContext context)
        {
            _context = context;
        }

        // GET: Employees
        [ResponseCache(Location = ResponseCacheLocation.Any, Duration = 270)]
        public async Task<IActionResult>  Index(int? fullName, int? age, double? salary, double? raiting,
                                   int page = 1, SortStateEmployee employeeSort = SortStateEmployee.FullNameAsc)
        {
            //фильтрация
            IQueryable<Employee> companyContext = _context.Employees
                                                   .Include(d => d.Departament);
            if (fullName != null && fullName != 0)
            {
                companyContext = companyContext.Where(d => d.Id == fullName);
            }
            if (age != null && age.Value != 0)
            {
                companyContext = companyContext.Where(d => d.Age == age);
            }
            if (salary != null && salary.Value != 0)
            {
                companyContext = companyContext.Where(d => d.Salary == salary);
            }
            if (raiting != null && raiting.Value != 0)
            {
                companyContext = companyContext.Where(d => d.Raiting == raiting);
            }
            //сортировка
            switch (employeeSort)
            {
                case SortStateEmployee.AgeAsc:
                    companyContext = companyContext.OrderBy(d => d.Age);
                    break;
                case SortStateEmployee.AgeDesc:
                    companyContext = companyContext.OrderByDescending(d => d.Age);
                    break;
                case SortStateEmployee.FullNameAsc:
                    companyContext = companyContext.OrderBy(d => d.FullName);
                    break;
                case SortStateEmployee.FullNameDesc:
                    companyContext = companyContext.OrderByDescending(d => d.FullName);
                    break;
                case SortStateEmployee.SalaryAsc:
                    companyContext = companyContext.OrderBy(d => d.Salary);
                    break;
                case SortStateEmployee.SalaryDesc:
                    companyContext = companyContext.OrderByDescending(d => d.Salary);
                    break;
                case SortStateEmployee.RaitingAsc:
                    companyContext = companyContext.OrderBy(d => d.Raiting);
                    break;
                case SortStateEmployee.RaitingDesc:
                    companyContext = companyContext.OrderByDescending(d => d.Raiting);
                    break;
                case SortStateEmployee.DepartamentAsc:
                    companyContext = companyContext.OrderBy(d => d.Departament.FullName);
                    break;
                case SortStateEmployee.DepartamentDesc:
                    companyContext = companyContext.OrderByDescending(d => d.Departament.FullName);
                    break;
                default:
                    companyContext = companyContext.OrderBy(d => d.FullName);
                    break;
            }

            //разбиение на страницы
            var count = await companyContext.CountAsync();
            var companys = await companyContext.Skip((page - 1) * pageSize).Take(pageSize).ToListAsync();

            //формирование представления
            IndexEmployeeViewModel employeesView = new IndexEmployeeViewModel
            {
                Employees = companys,
                PageViewModel = new PageViewModel(count, page, pageSize),
                SortEmployeeViewModel = new SortEmployeeViewModel(employeeSort),
                FilterEmployeeViewModel = new FilterEmployeeViewModel(companyContext.ToList(), fullName, age, salary, raiting)
            };
            return View(employeesView);
        }

        // GET: Employees/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var employee = await _context.Employees
                .Include(e => e.Departament)
                .FirstOrDefaultAsync(m => m.Id == id);
            if (employee == null)
            {
                return NotFound();
            }

            return View(employee);
        }

        // GET: Employees/Create
        public IActionResult Create()
        {
            ViewData["DepartamentId"] = new SelectList(_context.Departaments, "Id", "FullName");
            return View();
        }

        // POST: Employees/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id,FullName,Salary,Age,Raiting,DepartamentId")] Employee employee)
        {
            if (ModelState.IsValid)
            {
                _context.Add(employee);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            ViewData["DepartamentId"] = new SelectList(_context.Departaments, "Id", "FullName", employee.DepartamentId);
            return View(employee);
        }

        // GET: Employees/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var employee = await _context.Employees.FindAsync(id);
            if (employee == null)
            {
                return NotFound();
            }
            ViewData["DepartamentId"] = new SelectList(_context.Departaments, "Id", "FullName", employee.DepartamentId);
            return View(employee);
        }

        // POST: Employees/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Id,FullName,Salary,Age,Raiting,DepartamentId")] Employee employee)
        {
            if (id != employee.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(employee);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!EmployeeExists(employee.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            ViewData["DepartamentId"] = new SelectList(_context.Departaments, "Id", "FullName", employee.DepartamentId);
            return View(employee);
        }

        // GET: Employees/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var employee = await _context.Employees
                .Include(e => e.Departament)
                .FirstOrDefaultAsync(m => m.Id == id);
            if (employee == null)
            {
                return NotFound();
            }

            return View(employee);
        }

        // POST: Employees/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var employee = await _context.Employees.FindAsync(id);
            _context.Employees.Remove(employee);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool EmployeeExists(int id)
        {
            return _context.Employees.Any(e => e.Id == id);
        }
       
    }
}

Company/Company/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <title>@ViewData["Title"] - Company</title>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
</head>

<body>
    <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
        <a class="navbar-brand">Company</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>

        <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav mr-auto">
                <li class="nav-item">
                    <a class="nav-link" asp-controller="Home" asp-action="Index">Home</a>
                </li>

                <li class="nav-item dropdown">
                    <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                        Данные о сотрудниках
                    </a>
                    <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                        <a class="dropdown-item" asp-controller="EmployeeFacts" asp-action="Index">Фактические показатели сотрудников</a>
                        <a class="dropdown-item" asp-controller="EmployeePlans" asp-action="Index">Плановые показатели сотрдников</a>
                        <a class="dropdown-item" asp-controller="Employees" asp-action="Index">Сотрудники</a>
                        <a class="dropdown-item" asp-controller="ProgressEmployees" asp-action="Index">Прогресс сотрудников</a>
                        <a class="dropdown-item" asp-controller="ListEmployeesMetrics" asp-action="Index">Перечень показателей оценки деятельности сотрудников</a>
                        <div class="dropdown-divider"></div>
                    </div>
                </li>

                <li class="nav-item dropdown">
                    <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                        Данные о подразделениях
                    </a>
                    <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                        <a class="dropdown-item" asp-controller="Departaments" asp-action="Index">Подразделения</a>
                        <a class="dropdown-item" asp-controller="DepartamentValuationFacts" asp-action="Index">Фактические показатели подразделений</a>
                        <a class="dropdown-item" asp-controller="DepartamentValuationPlans" asp-action="Index">Плановые показатели подразделений</a>
                        <a class="dropdown-item" asp-controller="ListDepartamentMetrics" asp-action="Index">Перечень показателей оценки деятельности подразделений</a>
                        <div class="dropdown-divider"></div>
                    </div>
                </li>
            </ul>
        </div>
    </nav>

    <div class="container body-content">
        @RenderBody()
        <footer>
            <p>&copy; 2019 - Company</p>
        </footer>
    </div>

    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="https://code.jquery.com/jquery-3.4.1.slim.min.js" integrity="sha384-J6qa4849blE2+poT4WnyKhv5vZF5SrPo0iEjwBvKU7imGFAV0wwj1yYfoRSJoZ+n" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js" integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6" crossorigin="anonymous"></script>
    @RenderSection("Scripts", required: false)
</body>
</html>